CC=g++


CFLAGS= -std=c++11

Recompile: Prog

Prog:
	$(CC) $(CFLAGS) -o a.out String.cpp Gene.cpp DnaQueue.cpp main.cpp

Tar:
	 tar -cvf FinalProjectpartB.tar String.cpp Gene.cpp DnaQueue.cpp main.cpp String.h Gene.h DnaQueue.h stamp.sh Makefile README.txt FinalReportSummary.odt FinalReportSummary.pdf 
Clean:
	rm a.out
	rm FinalProjectpartB.tar
